version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
    groups:
      test:
        patterns:
        - "ci_reporter*"
        - "climate_control"
        - "factory_bot*"
        - "rspec-*"
        - "shoulda*"
        - "timecop"
        - "simplecov"
        - "webmock"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
